/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfoPanel: typeof import('./src/components/InfoPanel.vue')['default']
    MainDisplay: typeof import('./src/components/MainDisplay.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarTest: typeof import('./src/components/SidebarTest.vue')['default']
    TestCanvas: typeof import('./src/components/TestCanvas.vue')['default']
  }
}
